[package]
name = "reedition"
description = "Helper macro for the rust-2018 crate"
repository = "https://github.com/m-ou-se/reedition"
version = "1.0.0"
license = "BSD-2-Clause"
edition = "2018"

[lib]
proc_macro = true
