[package]
name = "rust-2015"
description = "Macro to use Rust 2015 from all editions"
repository = "https://github.com/m-ou-se/edition"
version = "1.0.0"
license = "BSD-2-Clause"
edition = "2015"

[dependencies]
reedition = { version = "=1.0.0", path = "../reedition" }
