[package]
name = "rust-2021"
description = "Macro to use Rust 2021 from all editions"
repository = "https://github.com/m-ou-se/edition"
version = "1.0.1"
license = "BSD-2-Clause"
edition = "2021"

[dependencies]
reedition = { version = "=1.0.0", path = "../reedition" }
